export const animes = [
    {
        id: "1",
        name: "Demon Slayer: Kimetsu no Yaiba",
        image: "/images/kny.jpg",
        genre: ["Action", "Historical", "Shounen"],
        rating: "9.2",
    },
    {
        id: "2",
        name: "Kono Subarashii Sekai ni Shukufuku wo!",
        image: "/images/konosuba.jpg",
        genre: ["Adventure", "Comedy", "Fantasy"],
        rating: "9.2",
    },
    {
        id: "3",
        name: "Haikyuu!!",
        image: "/images/haikyuu.jpg",
        genre: ["Sport", "Comedy", "Shounen"],
        rating: "9.2",
    },
    {
        id: "4",
        name: "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
        image: "/images/danmachi.jpg",
        genre: ["Action", "Comedy", "Shounen"],
        rating: "9.2",
    },
    {
        id: "5",
        name: "Sword Art Online",
        image: "/images/sao.jpg",
        genre: ["Action", "Fantasy", "Shounen"],
        rating: "9.2",
    },
    {
        id: "6",
        name: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
        image: "/images/seishun-buta.jpg",
        genre: ["Drama", "Romance"],
        rating: "9.2",
    },
    {
        id: "7",
        name: "Angel Beats!",
        image: "/images/angel-beats.jpg",
        genre: ["Drama", "Fantasy"],
        rating: "8.5",
    },
    {
        id: "8",
        name: "Charlotte",
        image: "/images/charlotte.jpg",
        genre: ["Drama", "School", "Super Power"],
        rating: "8.2",
    },
    {
        id: "9",
        name: "K-On!",
        image: "/images/k-on.jpg",
        genre: ["Comedy", "Music", "School"],
        rating: "8.4",
    },
];
